name: SendDataUpdatedEmail

on:
  workflow_run:
    workflows: [MergeRecents]
      
    types:
      - completed  

  workflow_dispatch:

jobs:
  scheduled-submit:
  
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.repository_owner == 'european-modelling-hubs' }}    
    runs-on: ubuntu-latest
    
    steps:
    
      - name: Get previous workflow run
        id: get_previous_run
        uses: actions/github-script@v6
        with:
          script: |
            const response = await github.rest.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'import_truth.yml',
              per_page: 1,
            });
            const lastRun = response.data.workflow_runs[0];
            core.setOutput('conclusion', lastRun.conclusion || 'no_run'); 


      - name: Debug
        run: |
          echo "Previous run result: ${{ steps.get_previous_run.outputs.conclusion }}"

      - name: Send warning email to admin
        if: ${{ steps.get_previous_run.outputs.conclusion != 'success' }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "RespiCast-SyndromicIndicators - Target data error!"
          body: "Hi,\n\nAn error occurred during ERVISS data import process. Not sending data updated email to teams!\n\nRespiCast tech team."
          to: paolo.milano@isi.it,corrado.gioannini@isi.it,nicolo.gozzi@isi.it
          from: "Respicast Team <respicast@isi.it>"
          content_type: text/plain

          
      - name: Cancel workflow if last run was not successful 
        if: ${{ steps.get_previous_run.outputs.conclusion != 'success' }}
        run: |
          echo "Check run was NOT successful. Not sending emails."
          exit 1 # Stop workflow run


      # Install Python
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

         
      # Checkout the python tools repo
      # -------------------------------------------      
      - name: Checkout repository
        uses: actions/checkout@v4
        

      # Checkout the python tools repo
      # used to verify the PR changes 
      # ------------------------------------------
      - name: checkout python tools repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: 'european-modelling-hubs/hub-tools'
          ref: 'main'
          path: tools

      - name: install deps
        run: |
          pip install PyYAML


      # Check if some submission is outside allowed folders
      - name: Extract Mailing List
        id: extract_from_metadata
        run: |
          python ./tools/code/extract_emails.py --folder_path "model-metadata"  "--exclusions" "respicast-hubEnsemble.yml respicast-quantileBaseline.yml"
        
      # Send the email
      - name: Send email to teams
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "RespiCast-SyndromicIndicators Data Update"
          body: ${{ secrets.EMAIL_TEXT }}
          to: respicast@isi.it
          bcc: ${{ steps.extract_from_metadata.outputs.email_list }}
          from: "Respicast Team <respicast@isi.it>"
          content_type: text/plain
